function pFy = Fun_pFy(pAy,qF,dFx,dFy)
%FUN_PFY
%    PFY = FUN_PFY(PAY,QF,DFX,DFY)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 01:52:23

pFy = pAy+dFy.*cos(qF)+dFx.*sin(qF);
