function pFdotx = Fun_pFdotx(pAx,qF,pAdotx,qFdot,dFx,dFy)
%FUN_PFDOTX
%    PFDOTX = FUN_PFDOTX(PAX,QF,PADOTX,QFDOT,DFX,DFY)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 01:52:23

pFdotx = pAdotx-qFdot.*(dFy.*cos(qF)+dFx.*sin(qF));
