function pFdoty = Fun_pFdoty(pAy,qF,pAdoty,qFdot,dFx,dFy)
%FUN_PFDOTY
%    PFDOTY = FUN_PFDOTY(PAY,QF,PADOTY,QFDOT,DFX,DFY)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 01:52:23

pFdoty = pAdoty+qFdot.*(dFx.*cos(qF)-dFy.*sin(qF));
