function JT_Fy = Fun_Contact_Sim_JT_Fy(R,k,c,y,ydot)
%FUN_CONTACT_SIM_JT_FY
%    JT_FY = FUN_CONTACT_SIM_JT_FY(R,K,C,Y,YDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 01:52:21

t2 = R-y;
t15 = R.*3.0e2;
t16 = y.*3.0e2;
t17 = t15-t16;
t3 = tanh(t17);
t4 = k.^(2.0./3.0);
t5 = ydot.*5.0e1;
t6 = 1.0./c;
t20 = t6.*(1.0e2./3.0);
t7 = t5-t20;
t8 = tanh(t7);
t9 = t8.*(1.0./2.0);
t10 = t9-5.000000000000001e-1;
t11 = t2.^2;
t12 = t11+1.0e-5;
t13 = c.*ydot.*(3.0./2.0);
t14 = t13-1.0;
t18 = R.*t4.*(1.0./2.0);
t19 = sqrt(t18);
t21 = t12.^(3.0./4.0);
t22 = t3.*(1.0./2.0);
t23 = t22+5.000000000000001e-1;
JT_Fy = [t4.*t10.*t14.*t19.*t21.*(t3.^2.*1.5e2-1.5e2).*(2.0./3.0)-t4.*t10.*1.0./t12.^(1.0./4.0).*t14.*t19.*t23.*(R.*2.0-y.*2.0).*(1.0./2.0);c.*t4.*t10.*t19.*t21.*t23-t4.*t14.*t19.*t21.*t23.*(t8.^2.*2.5e1-2.5e1).*(2.0./3.0)];
