function yrsmddot = Fun_yrsmddot(in1,in2,in3,in4)
%FUN_YRSMDDOT
%    YRSMDDOT = FUN_YRSMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:43

Lsm = in4(:,6);
Lt = in4(:,3);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qrh = in1(:,4);
qrhdot = in2(:,4);
qrhddot = in3(:,4);
qrk = in1(:,5);
qrkdot = in2(:,5);
qrkddot = in3(:,5);
ybddot = in3(:,2);
t2 = qb+qrh;
t3 = sin(t2);
t4 = Lt.*t3;
t5 = qb+qrh+qrk;
t6 = sin(t5);
t7 = Lsm.*t6;
t8 = t4+t7;
t9 = cos(t5);
t10 = cos(t2);
t11 = Lt.*t10;
t12 = Lsm.*t9;
t13 = t11+t12;
t14 = Lsm.*qrkdot.*t9;
t15 = qbdot.*t13;
t16 = qrhdot.*t13;
t17 = t14+t15+t16;
yrsmddot = ybddot+qbdot.*t17+qbddot.*t8+qrhdot.*t17+qrhddot.*t8+qrkdot.*(t14+Lsm.*qbdot.*t9+Lsm.*qrhdot.*t9)+Lsm.*qrkddot.*t6;
