function ylfm = Fun_ylfm(in1,in2)
%FUN_YLFM
%    YLFM = FUN_YLFM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Ls = in2(:,5);
Lt = in2(:,3);
dfmx = in2(:,11);
dfmy = in2(:,12);
qb = in1(:,3);
qla = in1(:,9);
qlh = in1(:,7);
qlk = in1(:,8);
yb = in1(:,2);
t2 = qb+qla+qlh+qlk;
ylfm = yb-Lt.*cos(qb+qlh)+dfmy.*cos(t2)+dfmx.*sin(t2)-Ls.*cos(qb+qlh+qlk);
