function qls = Fun_qls(in1)
%FUN_QLS
%    QLS = FUN_QLS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:30

qb = in1(:,3);
qlh = in1(:,7);
qlk = in1(:,8);
qls = qb+qlh+qlk;
