function qlfdot = Fun_qlfdot(in1)
%FUN_QLFDOT
%    QLFDOT = FUN_QLFDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbdot = in1(:,3);
qladot = in1(:,9);
qlhdot = in1(:,7);
qlkdot = in1(:,8);
qlfdot = qbdot+qladot+qlhdot+qlkdot;
