function xrtm = Fun_xrtm(in1,in2)
%FUN_XRTM
%    XRTM = FUN_XRTM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:34

Ltm = in2(:,4);
qb = in1(:,3);
qrh = in1(:,4);
xb = in1(:,1);
xrtm = xb+Ltm.*sin(qb+qrh);
