function ybmddot = Fun_ybmddot(in1,in2,in3,in4)
%FUN_YBMDDOT
%    YBMDDOT = FUN_YBMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:43

Lbm = in4(:,2);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
ybddot = in3(:,2);
ybmddot = ybddot-Lbm.*qbddot.*sin(qb)-Lbm.*qbdot.^2.*cos(qb);
