function qrfdot = Fun_qrfdot(in1)
%FUN_QRFDOT
%    QRFDOT = FUN_QRFDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbdot = in1(:,3);
qradot = in1(:,6);
qrhdot = in1(:,4);
qrkdot = in1(:,5);
qrfdot = qbdot+qradot+qrhdot+qrkdot;
