function xrfm = Fun_xrfm(in1,in2)
%FUN_XRFM
%    XRFM = FUN_XRFM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:34

Ls = in2(:,5);
Lt = in2(:,3);
dfmx = in2(:,11);
dfmy = in2(:,12);
qb = in1(:,3);
qra = in1(:,6);
qrh = in1(:,4);
qrk = in1(:,5);
xb = in1(:,1);
t2 = qb+qra+qrh+qrk;
xrfm = xb+Lt.*sin(qb+qrh)+dfmx.*cos(t2)-dfmy.*sin(t2)+Ls.*sin(qb+qrh+qrk);
