function xrto = Fun_xrto(in1,in2)
%FUN_XRTO
%    XRTO = FUN_XRTO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:34

Ls = in2(:,5);
Lt = in2(:,3);
dtox = in2(:,9);
dtoy = in2(:,10);
qb = in1(:,3);
qra = in1(:,6);
qrh = in1(:,4);
qrk = in1(:,5);
xb = in1(:,1);
t2 = qb+qra+qrh+qrk;
xrto = xb+Lt.*sin(qb+qrh)+dtox.*cos(t2)-dtoy.*sin(t2)+Ls.*sin(qb+qrh+qrk);
