function qlt = Fun_qlt(in1)
%FUN_QLT
%    QLT = FUN_QLT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:30

qb = in1(:,3);
qlh = in1(:,7);
qlt = qb+qlh;
