function qlsddot = Fun_qlsddot(in1)
%FUN_QLSDDOT
%    QLSDDOT = FUN_QLSDDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbddot = in1(:,3);
qlhddot = in1(:,7);
qlkddot = in1(:,8);
qlsddot = qbddot+qlhddot+qlkddot;
