function qrtdot = Fun_qrtdot(in1)
%FUN_QRTDOT
%    QRTDOT = FUN_QRTDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbdot = in1(:,3);
qrhdot = in1(:,4);
qrtdot = qbdot+qrhdot;
