function ylsm = Fun_ylsm(in1,in2)
%FUN_YLSM
%    YLSM = FUN_YLSM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Lsm = in2(:,6);
Lt = in2(:,3);
qb = in1(:,3);
qlh = in1(:,7);
qlk = in1(:,8);
yb = in1(:,2);
ylsm = yb-Lt.*cos(qb+qlh)-Lsm.*cos(qb+qlh+qlk);
