function JT_Fx = Fun_Contact_Sim_JT_Fx(R,k,c,ud,V,y,ydot,xdot)
%FUN_CONTACT_SIM_JT_FX
%    JT_FX = FUN_CONTACT_SIM_JT_FX(R,K,C,UD,V,Y,YDOT,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:20

t2 = R-y;
t18 = R.*3.0e2;
t19 = y.*3.0e2;
t20 = t18-t19;
t3 = tanh(t20);
t4 = k.^(2.0./3.0);
t5 = 1.0./V;
t6 = t5.*xdot;
t7 = tanh(t6);
t8 = ydot.*5.0e1;
t9 = 1.0./c;
t26 = t9.*(1.0e2./3.0);
t10 = t8-t26;
t11 = tanh(t10);
t12 = t11.*(1.0./2.0);
t13 = t12-5.000000000000001e-1;
t14 = t2.^2;
t15 = t14+1.0e-5;
t16 = c.*ydot.*(3.0./2.0);
t17 = t16-1.0;
t21 = R.*t4.*(1.0./2.0);
t22 = sqrt(t21);
t23 = t15.^(3.0./4.0);
t24 = t3.*(1.0./2.0);
t25 = t24+5.000000000000001e-1;
JT_Fx = [t4.*t7.*t13.*t17.*t22.*t23.*ud.*(t3.^2.*1.5e2-1.5e2).*(-2.0./3.0)+t4.*t7.*t13.*1.0./t15.^(1.0./4.0).*t17.*t22.*t25.*ud.*(R.*2.0-y.*2.0).*(1.0./2.0);t4.*t7.*t17.*t22.*t23.*t25.*ud.*(t11.^2.*2.5e1-2.5e1).*(2.0./3.0)-c.*t4.*t7.*t13.*t22.*t23.*t25.*ud;t4.*t5.*t13.*t17.*t22.*t23.*t25.*ud.*(t7.^2-1.0).*(2.0./3.0)];
