function qrf = Fun_qrf(in1)
%FUN_QRF
%    QRF = FUN_QRF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:30

qb = in1(:,3);
qra = in1(:,6);
qrh = in1(:,4);
qrk = in1(:,5);
qrf = qb+qra+qrh+qrk;
