function qlfddot = Fun_qlfddot(in1)
%FUN_QLFDDOT
%    QLFDDOT = FUN_QLFDDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:32

qbddot = in1(:,3);
qladdot = in1(:,9);
qlhddot = in1(:,7);
qlkddot = in1(:,8);
qlfddot = qbddot+qladdot+qlhddot+qlkddot;
