function xrtmddot = Fun_xrtmddot(in1,in2,in3,in4)
%FUN_XRTMDDOT
%    XRTMDDOT = FUN_XRTMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:43

Ltm = in4(:,4);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qrh = in1(:,4);
qrhdot = in2(:,4);
qrhddot = in3(:,4);
xbddot = in3(:,1);
t2 = qb+qrh;
t3 = sin(t2);
t4 = Ltm.*qbdot.*t3;
t5 = Ltm.*qrhdot.*t3;
t6 = t4+t5;
t7 = cos(t2);
xrtmddot = xbddot-qbdot.*t6-qrhdot.*t6+Ltm.*qbddot.*t7+Ltm.*qrhddot.*t7;
