function qrfddot = Fun_qrfddot(in1)
%FUN_QRFDDOT
%    QRFDDOT = FUN_QRFDDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbddot = in1(:,3);
qraddot = in1(:,6);
qrhddot = in1(:,4);
qrkddot = in1(:,5);
qrfddot = qbddot+qraddot+qrhddot+qrkddot;
