function Flgy = Fun_Flgy(in1,in2,in3,in4)
%FUN_FLGY
%    FLGY = FUN_FLGY(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:55

cts_FLy1 = in4(:,1);
cts_FLy2 = in4(:,2);
cts_FLy3 = in4(:,3);
cts_FLy4 = in4(:,4);
cts_FLy5 = in4(:,5);
Flgy = cts_FLy1+cts_FLy2+cts_FLy3+cts_FLy4+cts_FLy5;
