function xlfm = Fun_xlfm(in1,in2)
%FUN_XLFM
%    XLFM = FUN_XLFM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Ls = in2(:,5);
Lt = in2(:,3);
dfmx = in2(:,11);
dfmy = in2(:,12);
qb = in1(:,3);
qla = in1(:,9);
qlh = in1(:,7);
qlk = in1(:,8);
xb = in1(:,1);
t2 = qb+qla+qlh+qlk;
xlfm = xb+Lt.*sin(qb+qlh)+dfmx.*cos(t2)-dfmy.*sin(t2)+Ls.*sin(qb+qlh+qlk);
