function qlf = Fun_qlf(in1)
%FUN_QLF
%    QLF = FUN_QLF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qb = in1(:,3);
qla = in1(:,9);
qlh = in1(:,7);
qlk = in1(:,8);
qlf = qb+qla+qlh+qlk;
