function xrctsdot = Fun_xrctsdot(in1,in2,in3,in4,in5)
%FUN_XRCTSDOT
%    XRCTSDOT = FUN_XRCTSDOT(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:41

Ls = in3(:,5);
Lt = in3(:,3);
ctsx1 = in4(:,1);
ctsx2 = in4(:,2);
ctsy1 = in5(:,1);
ctsx3 = in4(:,3);
ctsy2 = in5(:,2);
ctsx4 = in4(:,4);
ctsy3 = in5(:,3);
ctsx5 = in4(:,5);
ctsy4 = in5(:,4);
ctsy5 = in5(:,5);
qb = in1(:,3);
qbdot = in2(:,3);
qra = in1(:,6);
qradot = in2(:,6);
qrh = in1(:,4);
qrhdot = in2(:,4);
qrk = in1(:,5);
qrkdot = in2(:,5);
xbdot = in2(:,1);
t2 = qb+qra+qrh+qrk;
t3 = cos(t2);
t4 = ctsy1.*t3;
t5 = sin(t2);
t6 = ctsx1.*t5;
t7 = qb+qrh+qrk;
t8 = cos(t7);
t9 = qb+qrh;
t10 = cos(t9);
t12 = Ls.*t8;
t15 = Lt.*t10;
t11 = t4+t6-t12-t15;
t13 = ctsy2.*t3;
t14 = ctsx2.*t5;
t16 = ctsy3.*t3;
t17 = ctsx3.*t5;
t18 = ctsy4.*t3;
t19 = ctsx4.*t5;
t20 = ctsy5.*t3;
t21 = ctsx5.*t5;
xrctsdot = [xbdot-qradot.*(t4+t6)-qrkdot.*(t4+t6-Ls.*t8)-qbdot.*t11-qrhdot.*t11,xbdot-qradot.*(t13+t14)+qbdot.*(t12-t13-t14+t15)+qrhdot.*(t12-t13-t14+t15)-qrkdot.*(-t12+t13+t14),xbdot-qradot.*(t16+t17)+qbdot.*(t12+t15-t16-t17)+qrhdot.*(t12+t15-t16-t17)-qrkdot.*(-t12+t16+t17),xbdot-qradot.*(t18+t19)+qbdot.*(t12+t15-t18-t19)+qrhdot.*(t12+t15-t18-t19)-qrkdot.*(-t12+t18+t19),xbdot-qradot.*(t20+t21)+qbdot.*(t12+t15-t20-t21)+qrhdot.*(t12+t15-t20-t21)-qrkdot.*(-t12+t20+t21)];
