function ylto = Fun_ylto(in1,in2)
%FUN_YLTO
%    YLTO = FUN_YLTO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:36

Ls = in2(:,5);
Lt = in2(:,3);
dtox = in2(:,9);
dtoy = in2(:,10);
qb = in1(:,3);
qla = in1(:,9);
qlh = in1(:,7);
qlk = in1(:,8);
yb = in1(:,2);
t2 = qb+qla+qlh+qlk;
ylto = yb-Lt.*cos(qb+qlh)+dtoy.*cos(t2)+dtox.*sin(t2)-Ls.*cos(qb+qlh+qlk);
