function yrto = Fun_yrto(in1,in2)
%FUN_YRTO
%    YRTO = FUN_YRTO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Ls = in2(:,5);
Lt = in2(:,3);
dtox = in2(:,9);
dtoy = in2(:,10);
qb = in1(:,3);
qra = in1(:,6);
qrh = in1(:,4);
qrk = in1(:,5);
yb = in1(:,2);
t2 = qb+qra+qrh+qrk;
yrto = yb-Lt.*cos(qb+qrh)+dtoy.*cos(t2)+dtox.*sin(t2)-Ls.*cos(qb+qrh+qrk);
