function qrt = Fun_qrt(in1)
%FUN_QRT
%    QRT = FUN_QRT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:30

qb = in1(:,3);
qrh = in1(:,4);
qrt = qb+qrh;
