function xltm = Fun_xltm(in1,in2)
%FUN_XLTM
%    XLTM = FUN_XLTM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Ltm = in2(:,4);
qb = in1(:,3);
qlh = in1(:,7);
xb = in1(:,1);
xltm = xb+Ltm.*sin(qb+qlh);
