function Frgy = Fun_Frgy(in1,in2,in3,in4)
%FUN_FRGY
%    FRGY = FUN_FRGY(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:55

cts_FRy1 = in2(:,1);
cts_FRy2 = in2(:,2);
cts_FRy3 = in2(:,3);
cts_FRy4 = in2(:,4);
cts_FRy5 = in2(:,5);
Frgy = cts_FRy1+cts_FRy2+cts_FRy3+cts_FRy4+cts_FRy5;
