function ylk = Fun_ylk(in1,in2)
%FUN_YLK
%    YLK = FUN_YLK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:33

Lt = in2(:,3);
qb = in1(:,3);
qlh = in1(:,7);
yb = in1(:,2);
ylk = yb-Lt.*cos(qb+qlh);
