function qltddot = Fun_qltddot(in1)
%FUN_QLTDDOT
%    QLTDDOT = FUN_QLTDDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbddot = in1(:,3);
qlhddot = in1(:,7);
qltddot = qbddot+qlhddot;
