function xlk = Fun_xlk(in1,in2)
%FUN_XLK
%    XLK = FUN_XLK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:33

Lt = in2(:,3);
qb = in1(:,3);
qlh = in1(:,7);
xb = in1(:,1);
xlk = xb+Lt.*sin(qb+qlh);
