function Mlg = Fun_Mlg(in1,in2,in3,in4,in5,in6)
%FUN_MLG
%    MLG = FUN_MLG(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:56

Ls = in6(:,5);
Lt = in6(:,3);
ctsx1 = in3(:,1);
ctsx2 = in3(:,2);
ctsy1 = in4(:,1);
ctsx3 = in3(:,3);
ctsy2 = in4(:,2);
ctsx4 = in3(:,4);
ctsy3 = in4(:,3);
ctsx5 = in3(:,5);
ctsy4 = in4(:,4);
ctsy5 = in4(:,5);
cts_FLx1 = in1(:,1);
cts_FLx2 = in1(:,2);
cts_FLy1 = in2(:,1);
cts_FLx3 = in1(:,3);
cts_FLy2 = in2(:,2);
cts_FLx4 = in1(:,4);
cts_FLy3 = in2(:,3);
cts_FLx5 = in1(:,5);
cts_FLy4 = in2(:,4);
cts_FLy5 = in2(:,5);
dfmx = in6(:,11);
dfmy = in6(:,12);
qb = in5(:,3);
qla = in5(:,9);
qlh = in5(:,7);
qlk = in5(:,8);
yb = in5(:,2);
t2 = qb+qla+qlh+qlk;
t3 = cos(t2);
t4 = dfmy.*t3;
t5 = qb+qlh;
t6 = cos(t5);
t7 = sin(t2);
t8 = dfmx.*t7;
t9 = qb+qlh+qlk;
t10 = cos(t9);
t12 = Lt.*t6;
t13 = Ls.*t10;
t11 = t4+t8-t12-t13+yb;
t14 = dfmy.*t7;
Mlg = cts_FLx1.*t11+cts_FLx2.*t11+cts_FLx3.*t11+cts_FLx4.*t11+cts_FLx5.*t11+cts_FLy1.*(t14+ctsx1.*t3-ctsy1.*t7-dfmx.*t3)+cts_FLy2.*(t14+ctsx2.*t3-ctsy2.*t7-dfmx.*t3)+cts_FLy3.*(t14+ctsx3.*t3-ctsy3.*t7-dfmx.*t3)+cts_FLy4.*(t14+ctsx4.*t3-ctsy4.*t7-dfmx.*t3)+cts_FLy5.*(t14+ctsx5.*t3-ctsy5.*t7-dfmx.*t3);
