function xn = Fun_xn(in1,in2)
%FUN_XN
%    XN = FUN_XN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:36

Lb = in2(:,1);
qb = in1(:,3);
xb = in1(:,1);
xn = xb-Lb.*sin(qb);
