function P_Joi = Fun_P_Joi(in1,in2)
%FUN_P_JOI
%    P_JOI = FUN_P_JOI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:56

Tla = in2(:,6);
Tlh = in2(:,4);
Tlk = in2(:,5);
Tra = in2(:,3);
Trh = in2(:,1);
Trk = in2(:,2);
qladot = in1(:,9);
qlhdot = in1(:,7);
qlkdot = in1(:,8);
qradot = in1(:,6);
qrhdot = in1(:,4);
qrkdot = in1(:,5);
P_Joi = [-Trh.*qrhdot,-Trk.*qrkdot,-Tra.*qradot,-Tlh.*qlhdot,-Tlk.*qlkdot,-Tla.*qladot];
