function xla = Fun_xla(in1,in2)
%FUN_XLA
%    XLA = FUN_XLA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:33

Ls = in2(:,5);
Lt = in2(:,3);
qb = in1(:,3);
qlh = in1(:,7);
qlk = in1(:,8);
xb = in1(:,1);
xla = xb+Lt.*sin(qb+qlh)+Ls.*sin(qb+qlh+qlk);
