function yltm = Fun_yltm(in1,in2)
%FUN_YLTM
%    YLTM = FUN_YLTM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Ltm = in2(:,4);
qb = in1(:,3);
qlh = in1(:,7);
yb = in1(:,2);
yltm = yb-Ltm.*cos(qb+qlh);
