function ylfmddot = Fun_ylfmddot(in1,in2,in3,in4)
%FUN_YLFMDDOT
%    YLFMDDOT = FUN_YLFMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:46

Ls = in4(:,5);
Lt = in4(:,3);
dfmx = in4(:,11);
dfmy = in4(:,12);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qla = in1(:,9);
qladot = in2(:,9);
qladdot = in3(:,9);
qlh = in1(:,7);
qlhdot = in2(:,7);
qlhddot = in3(:,7);
qlk = in1(:,8);
qlkdot = in2(:,8);
qlkddot = in3(:,8);
ybddot = in3(:,2);
t2 = qb+qla+qlh+qlk;
t3 = cos(t2);
t4 = dfmx.*t3;
t5 = sin(t2);
t6 = qb+qlh;
t7 = sin(t6);
t8 = Lt.*t7;
t9 = qb+qlh+qlk;
t10 = sin(t9);
t11 = Ls.*t10;
t27 = dfmy.*t5;
t12 = t4+t8+t11-t27;
t13 = dfmy.*t3;
t14 = dfmx.*t5;
t15 = cos(t9);
t16 = cos(t6);
t18 = Ls.*t15;
t23 = Lt.*t16;
t17 = t13+t14-t18-t23;
t19 = t13+t14-t18;
t20 = qlkdot.*t19;
t21 = t13+t14;
t22 = qladot.*t21;
t24 = qbdot.*t17;
t25 = qlhdot.*t17;
t26 = t20+t22+t24+t25;
ylfmddot = ybddot-qbdot.*t26+qbddot.*t12-qlhdot.*t26+qlhddot.*t12-qladot.*(t22+qbdot.*t21+qlhdot.*t21+qlkdot.*t21)+qladdot.*(t4-t27)-qlkdot.*(t20+t22+qbdot.*t19+qlhdot.*t19)+qlkddot.*(t4+t11-t27);
