function xlsm = Fun_xlsm(in1,in2)
%FUN_XLSM
%    XLSM = FUN_XLSM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Lsm = in2(:,6);
Lt = in2(:,3);
qb = in1(:,3);
qlh = in1(:,7);
qlk = in1(:,8);
xb = in1(:,1);
xlsm = xb+Lt.*sin(qb+qlh)+Lsm.*sin(qb+qlh+qlk);
