function J_PJoi = Fun_J_PJoi(in1,in2)
%FUN_J_PJOI
%    J_PJOI = FUN_J_PJOI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:56

Tla = in2(:,6);
Tlh = in2(:,4);
Tlk = in2(:,5);
Tra = in2(:,3);
Trh = in2(:,1);
Trk = in2(:,2);
qladot = in1(:,9);
qlhdot = in1(:,7);
qlkdot = in1(:,8);
qradot = in1(:,6);
qrhdot = in1(:,4);
qrkdot = in1(:,5);
J_PJoi = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-Trh,0.0,0.0,0.0,0.0,0.0,0.0,-Trk,0.0,0.0,0.0,0.0,0.0,0.0,-Tra,0.0,0.0,0.0,0.0,0.0,0.0,-Tlh,0.0,0.0,0.0,0.0,0.0,0.0,-Tlk,0.0,0.0,0.0,0.0,0.0,0.0,-Tla,-qrhdot,0.0,0.0,0.0,0.0,0.0,0.0,-qrkdot,0.0,0.0,0.0,0.0,0.0,0.0,-qradot,0.0,0.0,0.0,0.0,0.0,0.0,-qlhdot,0.0,0.0,0.0,0.0,0.0,0.0,-qlkdot,0.0,0.0,0.0,0.0,0.0,0.0,-qladot],[6,15]);
