function xlctsdot = Fun_xlctsdot(in1,in2,in3,in4,in5)
%FUN_XLCTSDOT
%    XLCTSDOT = FUN_XLCTSDOT(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:42

Ls = in3(:,5);
Lt = in3(:,3);
ctsx1 = in4(:,1);
ctsx2 = in4(:,2);
ctsy1 = in5(:,1);
ctsx3 = in4(:,3);
ctsy2 = in5(:,2);
ctsx4 = in4(:,4);
ctsy3 = in5(:,3);
ctsx5 = in4(:,5);
ctsy4 = in5(:,4);
ctsy5 = in5(:,5);
qb = in1(:,3);
qbdot = in2(:,3);
qla = in1(:,9);
qladot = in2(:,9);
qlh = in1(:,7);
qlhdot = in2(:,7);
qlk = in1(:,8);
qlkdot = in2(:,8);
xbdot = in2(:,1);
t2 = qb+qla+qlh+qlk;
t3 = cos(t2);
t4 = ctsy1.*t3;
t5 = sin(t2);
t6 = ctsx1.*t5;
t7 = qb+qlh+qlk;
t8 = cos(t7);
t9 = qb+qlh;
t10 = cos(t9);
t12 = Ls.*t8;
t15 = Lt.*t10;
t11 = t4+t6-t12-t15;
t13 = ctsy2.*t3;
t14 = ctsx2.*t5;
t16 = ctsy3.*t3;
t17 = ctsx3.*t5;
t18 = ctsy4.*t3;
t19 = ctsx4.*t5;
t20 = ctsy5.*t3;
t21 = ctsx5.*t5;
xlctsdot = [xbdot-qladot.*(t4+t6)-qlkdot.*(t4+t6-Ls.*t8)-qbdot.*t11-qlhdot.*t11,xbdot-qladot.*(t13+t14)+qbdot.*(t12-t13-t14+t15)+qlhdot.*(t12-t13-t14+t15)-qlkdot.*(-t12+t13+t14),xbdot-qladot.*(t16+t17)+qbdot.*(t12+t15-t16-t17)+qlhdot.*(t12+t15-t16-t17)-qlkdot.*(-t12+t16+t17),xbdot-qladot.*(t18+t19)+qbdot.*(t12+t15-t18-t19)+qlhdot.*(t12+t15-t18-t19)-qlkdot.*(-t12+t18+t19),xbdot-qladot.*(t20+t21)+qbdot.*(t12+t15-t20-t21)+qlhdot.*(t12+t15-t20-t21)-qlkdot.*(-t12+t20+t21)];
