function xra = Fun_xra(in1,in2)
%FUN_XRA
%    XRA = FUN_XRA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:33

Ls = in2(:,5);
Lt = in2(:,3);
qb = in1(:,3);
qrh = in1(:,4);
qrk = in1(:,5);
xb = in1(:,1);
xra = xb+Lt.*sin(qb+qrh)+Ls.*sin(qb+qrh+qrk);
