function yrtm = Fun_yrtm(in1,in2)
%FUN_YRTM
%    YRTM = FUN_YRTM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:34

Ltm = in2(:,4);
qb = in1(:,3);
qrh = in1(:,4);
yb = in1(:,2);
yrtm = yb-Ltm.*cos(qb+qrh);
