function qlsdot = Fun_qlsdot(in1)
%FUN_QLSDOT
%    QLSDOT = FUN_QLSDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbdot = in1(:,3);
qlhdot = in1(:,7);
qlkdot = in1(:,8);
qlsdot = qbdot+qlhdot+qlkdot;
