function yrk = Fun_yrk(in1,in2)
%FUN_YRK
%    YRK = FUN_YRK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:33

Lt = in2(:,3);
qb = in1(:,3);
qrh = in1(:,4);
yb = in1(:,2);
yrk = yb-Lt.*cos(qb+qrh);
