function yra = Fun_yra(in1,in2)
%FUN_YRA
%    YRA = FUN_YRA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:33

Ls = in2(:,5);
Lt = in2(:,3);
qb = in1(:,3);
qrh = in1(:,4);
qrk = in1(:,5);
yb = in1(:,2);
yra = yb-Lt.*cos(qb+qrh)-Ls.*cos(qb+qrh+qrk);
