function J_adot_Joi = Fun_J_adot_Joi(in1,in2,in3)
%FUN_J_ADOT_JOI
%    J_ADOT_JOI = FUN_J_ADOT_JOI(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:15

ala = in1(:,6);
alh = in1(:,4);
alk = in1(:,5);
ara = in1(:,3);
arh = in1(:,1);
ark = in1(:,2);
c1 = in3(:,1);
c2 = in3(:,2);
ula = in2(:,6);
ulh = in2(:,4);
ulk = in2(:,5);
ura = in2(:,3);
urh = in2(:,1);
urk = in2(:,2);
J_adot_Joi = reshape([-c2-c1.*urh,0.0,0.0,0.0,0.0,0.0,0.0,-c2-c1.*urk,0.0,0.0,0.0,0.0,0.0,0.0,-c2-c1.*ura,0.0,0.0,0.0,0.0,0.0,0.0,-c2-c1.*ulh,0.0,0.0,0.0,0.0,0.0,0.0,-c2-c1.*ulk,0.0,0.0,0.0,0.0,0.0,0.0,-c2-c1.*ula,c2+c1.*urh-c1.*(arh-urh),0.0,0.0,0.0,0.0,0.0,0.0,c2+c1.*urk-c1.*(ark-urk),0.0,0.0,0.0,0.0,0.0,0.0,c2+c1.*ura-c1.*(ara-ura),0.0,0.0,0.0,0.0,0.0,0.0,c2+c1.*ulh-c1.*(alh-ulh),0.0,0.0,0.0,0.0,0.0,0.0,c2+c1.*ulk-c1.*(alk-ulk),0.0,0.0,0.0,0.0,0.0,0.0,c2+c1.*ula-c1.*(ala-ula)],[6,12]);
