function xlsmddot = Fun_xlsmddot(in1,in2,in3,in4)
%FUN_XLSMDDOT
%    XLSMDDOT = FUN_XLSMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:45

Lsm = in4(:,6);
Lt = in4(:,3);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qlh = in1(:,7);
qlhdot = in2(:,7);
qlhddot = in3(:,7);
qlk = in1(:,8);
qlkdot = in2(:,8);
qlkddot = in3(:,8);
xbddot = in3(:,1);
t2 = qb+qlh;
t3 = sin(t2);
t4 = Lt.*t3;
t5 = qb+qlh+qlk;
t6 = sin(t5);
t7 = Lsm.*t6;
t8 = t4+t7;
t9 = qbdot.*t8;
t10 = qlhdot.*t8;
t11 = Lsm.*qlkdot.*t6;
t12 = t9+t10+t11;
t13 = cos(t2);
t14 = Lt.*t13;
t15 = cos(t5);
t16 = Lsm.*t15;
t17 = t14+t16;
xlsmddot = xbddot-qbdot.*t12+qbddot.*t17-qlhdot.*t12+qlhddot.*t17-qlkdot.*(t11+Lsm.*qbdot.*t6+Lsm.*qlhdot.*t6)+Lsm.*qlkddot.*t15;
