function Flgx = Fun_Flgx(in1,in2,in3,in4)
%FUN_FLGX
%    FLGX = FUN_FLGX(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:55

cts_FLx1 = in3(:,1);
cts_FLx2 = in3(:,2);
cts_FLx3 = in3(:,3);
cts_FLx4 = in3(:,4);
cts_FLx5 = in3(:,5);
Flgx = cts_FLx1+cts_FLx2+cts_FLx3+cts_FLx4+cts_FLx5;
