function ylsmddot = Fun_ylsmddot(in1,in2,in3,in4)
%FUN_YLSMDDOT
%    YLSMDDOT = FUN_YLSMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:45

Lsm = in4(:,6);
Lt = in4(:,3);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qlh = in1(:,7);
qlhdot = in2(:,7);
qlhddot = in3(:,7);
qlk = in1(:,8);
qlkdot = in2(:,8);
qlkddot = in3(:,8);
ybddot = in3(:,2);
t2 = qb+qlh;
t3 = sin(t2);
t4 = Lt.*t3;
t5 = qb+qlh+qlk;
t6 = sin(t5);
t7 = Lsm.*t6;
t8 = t4+t7;
t9 = cos(t5);
t10 = cos(t2);
t11 = Lt.*t10;
t12 = Lsm.*t9;
t13 = t11+t12;
t14 = Lsm.*qlkdot.*t9;
t15 = qbdot.*t13;
t16 = qlhdot.*t13;
t17 = t14+t15+t16;
ylsmddot = ybddot+qbdot.*t17+qbddot.*t8+qlhdot.*t17+qlhddot.*t8+qlkdot.*(t14+Lsm.*qbdot.*t9+Lsm.*qlhdot.*t9)+Lsm.*qlkddot.*t6;
