function yrfm = Fun_yrfm(in1,in2)
%FUN_YRFM
%    YRFM = FUN_YRFM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:34

Ls = in2(:,5);
Lt = in2(:,3);
dfmx = in2(:,11);
dfmy = in2(:,12);
qb = in1(:,3);
qra = in1(:,6);
qrh = in1(:,4);
qrk = in1(:,5);
yb = in1(:,2);
t2 = qb+qra+qrh+qrk;
yrfm = yb-Lt.*cos(qb+qrh)+dfmy.*cos(t2)+dfmx.*sin(t2)-Ls.*cos(qb+qrh+qrk);
