function qrtddot = Fun_qrtddot(in1)
%FUN_QRTDDOT
%    QRTDDOT = FUN_QRTDDOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbddot = in1(:,3);
qrhddot = in1(:,4);
qrtddot = qbddot+qrhddot;
