function qdotSeg = Fun_qdotSeg(in1)
%FUN_QDOTSEG
%    QDOTSEG = FUN_QDOTSEG(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:31

qbdot = in1(:,3);
qladot = in1(:,9);
qlhdot = in1(:,7);
qlkdot = in1(:,8);
qradot = in1(:,6);
qrhdot = in1(:,4);
qrkdot = in1(:,5);
qdotSeg = [qbdot+qrhdot;qbdot+qrhdot+qrkdot;qbdot+qradot+qrhdot+qrkdot;qbdot+qlhdot;qbdot+qlhdot+qlkdot;qbdot+qladot+qlhdot+qlkdot];
