function yrfmddot = Fun_yrfmddot(in1,in2,in3,in4)
%FUN_YRFMDDOT
%    YRFMDDOT = FUN_YRFMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:44

Ls = in4(:,5);
Lt = in4(:,3);
dfmx = in4(:,11);
dfmy = in4(:,12);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qra = in1(:,6);
qradot = in2(:,6);
qraddot = in3(:,6);
qrh = in1(:,4);
qrhdot = in2(:,4);
qrhddot = in3(:,4);
qrk = in1(:,5);
qrkdot = in2(:,5);
qrkddot = in3(:,5);
ybddot = in3(:,2);
t2 = qb+qra+qrh+qrk;
t3 = cos(t2);
t4 = dfmx.*t3;
t5 = sin(t2);
t6 = qb+qrh;
t7 = sin(t6);
t8 = Lt.*t7;
t9 = qb+qrh+qrk;
t10 = sin(t9);
t11 = Ls.*t10;
t27 = dfmy.*t5;
t12 = t4+t8+t11-t27;
t13 = dfmy.*t3;
t14 = dfmx.*t5;
t15 = cos(t9);
t16 = cos(t6);
t18 = Ls.*t15;
t23 = Lt.*t16;
t17 = t13+t14-t18-t23;
t19 = t13+t14-t18;
t20 = qrkdot.*t19;
t21 = t13+t14;
t22 = qradot.*t21;
t24 = qbdot.*t17;
t25 = qrhdot.*t17;
t26 = t20+t22+t24+t25;
yrfmddot = ybddot-qbdot.*t26+qbddot.*t12-qrhdot.*t26+qrhddot.*t12-qradot.*(t22+qbdot.*t21+qrhdot.*t21+qrkdot.*t21)+qraddot.*(t4-t27)-qrkdot.*(t20+t22+qbdot.*t19+qrhdot.*t19)+qrkddot.*(t4+t11-t27);
