function xrsmddot = Fun_xrsmddot(in1,in2,in3,in4)
%FUN_XRSMDDOT
%    XRSMDDOT = FUN_XRSMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:43

Lsm = in4(:,6);
Lt = in4(:,3);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qrh = in1(:,4);
qrhdot = in2(:,4);
qrhddot = in3(:,4);
qrk = in1(:,5);
qrkdot = in2(:,5);
qrkddot = in3(:,5);
xbddot = in3(:,1);
t2 = qb+qrh;
t3 = sin(t2);
t4 = Lt.*t3;
t5 = qb+qrh+qrk;
t6 = sin(t5);
t7 = Lsm.*t6;
t8 = t4+t7;
t9 = qbdot.*t8;
t10 = qrhdot.*t8;
t11 = Lsm.*qrkdot.*t6;
t12 = t9+t10+t11;
t13 = cos(t2);
t14 = Lt.*t13;
t15 = cos(t5);
t16 = Lsm.*t15;
t17 = t14+t16;
xrsmddot = xbddot-qbdot.*t12+qbddot.*t17-qrhdot.*t12+qrhddot.*t17-qrkdot.*(t11+Lsm.*qbdot.*t6+Lsm.*qrhdot.*t6)+Lsm.*qrkddot.*t15;
