function Frgx = Fun_Frgx(in1,in2,in3,in4)
%FUN_FRGX
%    FRGX = FUN_FRGX(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:55

cts_FRx1 = in1(:,1);
cts_FRx2 = in1(:,2);
cts_FRx3 = in1(:,3);
cts_FRx4 = in1(:,4);
cts_FRx5 = in1(:,5);
Frgx = cts_FRx1+cts_FRx2+cts_FRx3+cts_FRx4+cts_FRx5;
