function qrs = Fun_qrs(in1)
%FUN_QRS
%    QRS = FUN_QRS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:30

qb = in1(:,3);
qrh = in1(:,4);
qrk = in1(:,5);
qrs = qb+qrh+qrk;
