function ylctsdot = Fun_ylctsdot(in1,in2,in3,in4,in5)
%FUN_YLCTSDOT
%    YLCTSDOT = FUN_YLCTSDOT(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:42

Ls = in3(:,5);
Lt = in3(:,3);
ctsx1 = in4(:,1);
ctsx2 = in4(:,2);
ctsy1 = in5(:,1);
ctsx3 = in4(:,3);
ctsy2 = in5(:,2);
ctsx4 = in4(:,4);
ctsy3 = in5(:,3);
ctsx5 = in4(:,5);
ctsy4 = in5(:,4);
ctsy5 = in5(:,5);
qb = in1(:,3);
qbdot = in2(:,3);
qla = in1(:,9);
qladot = in2(:,9);
qlh = in1(:,7);
qlhdot = in2(:,7);
qlk = in1(:,8);
qlkdot = in2(:,8);
ybdot = in2(:,2);
t2 = qb+qla+qlh+qlk;
t3 = cos(t2);
t4 = ctsx1.*t3;
t5 = sin(t2);
t6 = qb+qlh;
t7 = sin(t6);
t8 = Lt.*t7;
t9 = qb+qlh+qlk;
t10 = sin(t9);
t11 = Ls.*t10;
t13 = ctsy1.*t5;
t12 = t4+t8+t11-t13;
t14 = ctsx2.*t3;
t16 = ctsy2.*t5;
t15 = t8+t11+t14-t16;
t17 = ctsx3.*t3;
t19 = ctsy3.*t5;
t18 = t8+t11+t17-t19;
t20 = ctsx4.*t3;
t22 = ctsy4.*t5;
t21 = t8+t11+t20-t22;
t23 = ctsx5.*t3;
t25 = ctsy5.*t5;
t24 = t8+t11+t23-t25;
ylctsdot = [ybdot+qbdot.*t12+qlhdot.*t12+qladot.*(t4-t13)+qlkdot.*(t4+t11-t13),ybdot+qbdot.*t15+qlhdot.*t15+qladot.*(t14-t16)+qlkdot.*(t11+t14-t16),ybdot+qbdot.*t18+qlhdot.*t18+qladot.*(t17-t19)+qlkdot.*(t11+t17-t19),ybdot+qbdot.*t21+qlhdot.*t21+qladot.*(t20-t22)+qlkdot.*(t11+t20-t22),ybdot+qbdot.*t24+qlhdot.*t24+qladot.*(t23-t25)+qlkdot.*(t11+t23-t25)];
