function yrhe = Fun_yrhe(in1,in2)
%FUN_YRHE
%    YRHE = FUN_YRHE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:34

Ls = in2(:,5);
Lt = in2(:,3);
dhex = in2(:,7);
dhey = in2(:,8);
qb = in1(:,3);
qra = in1(:,6);
qrh = in1(:,4);
qrk = in1(:,5);
yb = in1(:,2);
t2 = qb+qra+qrh+qrk;
yrhe = yb-Lt.*cos(qb+qrh)+dhey.*cos(t2)+dhex.*sin(t2)-Ls.*cos(qb+qrh+qrk);
