function adot_Joi = Fun_adot_Joi(in1,in2,in3)
%FUN_ADOT_JOI
%    ADOT_JOI = FUN_ADOT_JOI(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:15

ala = in1(:,6);
alh = in1(:,4);
alk = in1(:,5);
ara = in1(:,3);
arh = in1(:,1);
ark = in1(:,2);
c1 = in3(:,1);
c2 = in3(:,2);
ula = in2(:,6);
ulh = in2(:,4);
ulk = in2(:,5);
ura = in2(:,3);
urh = in2(:,1);
urk = in2(:,2);
adot_Joi = [-(arh-urh).*(c2+c1.*urh),-(ark-urk).*(c2+c1.*urk),-(ara-ura).*(c2+c1.*ura),-(alh-ulh).*(c2+c1.*ulh),-(alk-ulk).*(c2+c1.*ulk),-(ala-ula).*(c2+c1.*ula)];
