function J_T_Joi = Fun_J_T_Joi(in1)
%FUN_J_T_JOI
%    J_T_JOI = FUN_J_T_JOI(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:14

Tlamax = in1(:,6);
Tlhmax = in1(:,4);
Tlkmax = in1(:,5);
Tramax = in1(:,3);
Trhmax = in1(:,1);
Trkmax = in1(:,2);
J_T_Joi = reshape([Trhmax,0.0,0.0,0.0,0.0,0.0,0.0,Trkmax,0.0,0.0,0.0,0.0,0.0,0.0,Tramax,0.0,0.0,0.0,0.0,0.0,0.0,Tlhmax,0.0,0.0,0.0,0.0,0.0,0.0,Tlkmax,0.0,0.0,0.0,0.0,0.0,0.0,Tlamax],[6,6]);
