function ylcts = Fun_ylcts(in1,in2,in3,in4)
%FUN_YLCTS
%    YLCTS = FUN_YLCTS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:37

Ls = in2(:,5);
Lt = in2(:,3);
ctsx1 = in3(:,1);
ctsx2 = in3(:,2);
ctsy1 = in4(:,1);
ctsx3 = in3(:,3);
ctsy2 = in4(:,2);
ctsx4 = in3(:,4);
ctsy3 = in4(:,3);
ctsx5 = in3(:,5);
ctsy4 = in4(:,4);
ctsy5 = in4(:,5);
qb = in1(:,3);
qla = in1(:,9);
qlh = in1(:,7);
qlk = in1(:,8);
yb = in1(:,2);
t2 = qb+qla+qlh+qlk;
t3 = cos(t2);
t4 = qb+qlh;
t5 = cos(t4);
t6 = sin(t2);
t7 = qb+qlh+qlk;
t8 = cos(t7);
ylcts = [yb-Ls.*t8-Lt.*t5+ctsy1.*t3+ctsx1.*t6,yb-Ls.*t8-Lt.*t5+ctsy2.*t3+ctsx2.*t6,yb-Ls.*t8-Lt.*t5+ctsy3.*t3+ctsx3.*t6,yb-Ls.*t8-Lt.*t5+ctsy4.*t3+ctsx4.*t6,yb-Ls.*t8-Lt.*t5+ctsy5.*t3+ctsx5.*t6];
