function xlfmddot = Fun_xlfmddot(in1,in2,in3,in4)
%FUN_XLFMDDOT
%    XLFMDDOT = FUN_XLFMDDOT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:45

Ls = in4(:,5);
Lt = in4(:,3);
dfmx = in4(:,11);
dfmy = in4(:,12);
qb = in1(:,3);
qbdot = in2(:,3);
qbddot = in3(:,3);
qla = in1(:,9);
qladot = in2(:,9);
qladdot = in3(:,9);
qlh = in1(:,7);
qlhdot = in2(:,7);
qlhddot = in3(:,7);
qlk = in1(:,8);
qlkdot = in2(:,8);
qlkddot = in3(:,8);
xbddot = in3(:,1);
t2 = qb+qla+qlh+qlk;
t3 = cos(t2);
t4 = dfmx.*t3;
t5 = sin(t2);
t6 = qb+qlh+qlk;
t7 = sin(t6);
t8 = Ls.*t7;
t10 = dfmy.*t5;
t9 = t4+t8-t10;
t11 = t4-t10;
t12 = qladot.*t11;
t13 = qb+qlh;
t14 = sin(t13);
t15 = Lt.*t14;
t16 = t4+t8-t10+t15;
t17 = qlkdot.*t9;
t18 = qbdot.*t16;
t19 = qlhdot.*t16;
t20 = t12+t17+t18+t19;
t21 = dfmy.*t3;
t22 = dfmx.*t5;
t23 = cos(t6);
t24 = cos(t13);
t25 = t21+t22-Ls.*t23-Lt.*t24;
xlfmddot = xbddot-qladdot.*(t21+t22)-qlkddot.*(t21+t22-Ls.*t23)-qbdot.*t20-qbddot.*t25-qlhdot.*t20-qlhddot.*t25-qladot.*(t12+qbdot.*t11+qlhdot.*t11+qlkdot.*t11)-qlkdot.*(t12+t17+qbdot.*t9+qlhdot.*t9);
