function xlto = Fun_xlto(in1,in2)
%FUN_XLTO
%    XLTO = FUN_XLTO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:36

Ls = in2(:,5);
Lt = in2(:,3);
dtox = in2(:,9);
dtoy = in2(:,10);
qb = in1(:,3);
qla = in1(:,9);
qlh = in1(:,7);
qlk = in1(:,8);
xb = in1(:,1);
t2 = qb+qla+qlh+qlk;
xlto = xb+Lt.*sin(qb+qlh)+dtox.*cos(t2)-dtoy.*sin(t2)+Ls.*sin(qb+qlh+qlk);
