function J_yrcts = Fun_J_yrcts(in1,in2,in3,in4)
%FUN_J_YRCTS
%    J_YRCTS = FUN_J_YRCTS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:49

Ls = in2(:,5);
Lt = in2(:,3);
ctsx1 = in3(:,1);
ctsx2 = in3(:,2);
ctsy1 = in4(:,1);
ctsx3 = in3(:,3);
ctsy2 = in4(:,2);
ctsx4 = in3(:,4);
ctsy3 = in4(:,3);
ctsx5 = in3(:,5);
ctsy4 = in4(:,4);
ctsy5 = in4(:,5);
qb = in1(:,3);
qra = in1(:,6);
qrh = in1(:,4);
qrk = in1(:,5);
t2 = qb+qra+qrh+qrk;
t3 = cos(t2);
t4 = ctsx1.*t3;
t5 = sin(t2);
t6 = qb+qrh;
t7 = sin(t6);
t8 = Lt.*t7;
t9 = qb+qrh+qrk;
t10 = sin(t9);
t11 = Ls.*t10;
t13 = ctsy1.*t5;
t12 = t4+t8+t11-t13;
t14 = ctsx2.*t3;
t16 = ctsy2.*t5;
t15 = t8+t11+t14-t16;
t17 = ctsx3.*t3;
t19 = ctsy3.*t5;
t18 = t8+t11+t17-t19;
t20 = ctsx4.*t3;
t22 = ctsy4.*t5;
t21 = t8+t11+t20-t22;
t23 = ctsx5.*t3;
t25 = ctsy5.*t5;
t24 = t8+t11+t23-t25;
J_yrcts = reshape([0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,t12,t15,t18,t21,t24,t12,t15,t18,t21,t24,t4+t11-t13,t11+t14-t16,t11+t17-t19,t11+t20-t22,t11+t23-t25,t4-t13,t14-t16,t17-t19,t20-t22,t23-t25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,9]);
