function xlhe = Fun_xlhe(in1,in2)
%FUN_XLHE
%    XLHE = FUN_XLHE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:35

Ls = in2(:,5);
Lt = in2(:,3);
dhex = in2(:,7);
dhey = in2(:,8);
qb = in1(:,3);
qla = in1(:,9);
qlh = in1(:,7);
qlk = in1(:,8);
xb = in1(:,1);
t2 = qb+qla+qlh+qlk;
xlhe = xb+Lt.*sin(qb+qlh)+dhex.*cos(t2)-dhey.*sin(t2)+Ls.*sin(qb+qlh+qlk);
