function Fx = Fun_Contact_Sim_Fx(R,k,c,ud,V,y,ydot,xdot)
%FUN_CONTACT_SIM_FX
%    FX = FUN_CONTACT_SIM_FX(R,K,C,UD,V,Y,YDOT,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Nov-2020 15:44:20

t2 = R-y;
t3 = k.^(2.0./3.0);
Fx = t3.*ud.*tanh(xdot./V).*(t2.^2+1.0e-5).^(3.0./4.0).*(tanh(ydot.*5.0e1-(1.0e2./3.0)./c).*(1.0./2.0)-5.000000000000001e-1).*(c.*ydot.*(3.0./2.0)-1.0).*(tanh(R.*3.0e2-y.*3.0e2).*(1.0./2.0)+5.000000000000001e-1).*sqrt(R.*t3.*(1.0./2.0)).*(-2.0./3.0);
